name: Ping server

on:
  schedule:
  - cron: "22 15 9 7 *"

jobs:

  ping:
    name: ping server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Ping server
      run: |
         echo "About to ping server"
         npm install
         npm run ping -- ${{secret.API_KEY}}
         echo "Finished pinging server"